### ISSUE TITLE
Small Bug in src/generate.py

### ISSUE THREAD

**Issue by Luowaterbi** [princeton-nlp/CharXiv#3]
Should the code of line54 be `generate_fn(queries, args.model_path)` instead of `generate_fn(args.model_path, queries)`, since `def generate_response(queries, model_path=None):`?

**Comment by zwcolin** [comment]
Thanks for catching it! You are right that the function headers are mismatched for some models. It's due to previously merging those functions from our deprecated internal codebase. I will correct these cases (i.e., make `def generate_response(queries, model_path=None):` match the `generate_fn(queries, args.model_path)`.

**Comment by zwcolin** [comment]
The bug is fixed now and thank you for spotting it :)
