### ISSUE TITLE
Wrong prompr (DESCRIPTIVE_GRADING_ICL['title'])

### ISSUE THREAD

**Issue by JonghwanMun** [princeton-nlp/CharXiv#4]
https://github.com/princeton-nlp/CharXiv/blob/6d225db59213d2e7383f1e1017953e384d19cfd5/src/constants.py#L129-L150

for the above in-context example prompt at line 145-148, I think it needs to be modified as follows:
```
     { 
         "extract_answer_T1": "The number of students in each grade", 
         "score_T1": 0 
         "extract_answer_T2: "There is no title",  # here, wrong extracted answer: Not applicable -> There is no title
         "score_T2": 0   # here, wrong score: 1 -> 0
         "extract_answer_T3": "A_v^t", 
         "score_T3": 0    # here, wrong score: 1 -> 0
     } 
```

For the T2, it is quiet confusing when considering the rubric (`When ground truth answer is "Not Applicable", the response must express "Not Applicable" to receive a score of 1`). 
- The prediction 'there is no title' means not applicable, but, itself does not contain the expression 'not applicable'.
- It is confusing that the scoring model considers the prediction is correct or not. Thus, the modification would be wrong. 

Anyway, please double check the prompts. Thanks :)

**Comment by zwcolin** [comment]
> https://github.com/princeton-nlp/CharXiv/blob/6d225db59213d2e7383f1e1017953e384d19cfd5/src/constants.py#L129-L150
> 
> for the above in-context example prompt at line 145-148, I think it needs to be modified as follows:
> 
> ```
>      { 
>          "extract_answer_T1": "The number of students in each grade", 
>          "score_T1": 0 
>          "extract_answer_T2: "There is no title",  # here, wrong extracted answer: Not applicable -> There is no title
>          "score_T2": 0   # here, wrong score: 1 -> 0
>          "extract_answer_T3": "A_v^t", 
>          "score_T3": 0    # here, wrong score: 1 -> 0
>      } 
> ```
> 
> For the T2, it is quiet confusing when considering the rubric (`When ground truth answer is "Not Applicable", the response must express "Not Applicable" to receive a score of 1`).
> 
> * The prediction 'there is no title' means not applicable, but, itself does not contain the expression 'not applicable'.
> * It is confusing that the scoring model considers the prediction is correct or not. Thus, the modification would be wrong.
> 
> Anyway, please double check the prompts. Thanks :)

Thanks for your interest in CharXiv! 

> For the T2, it is quiet confusing when considering the rubric (When ground truth answer is "Not Applicable", the response must express "Not Applicable" to receive a score of 1).

We are a bit lenient in this aspect so basically want the grader to grant a score of 1 either when the model simply exactly follows the instruction by saying "Not Applicable" or expresses (i.e., implicitly) "Not Applicable", such as by saying "There is no title." In either case, the model's response is considered correct. We note that it appears that this gives a more lenient ICL for unanswerable questions for titles but not other descriptive questions, and we will fix this so that this ICL becomes stricter in CharXiv V2 in case we still plan to have these questions.

Note that all models have been evaluated in the same way and the ICL example itself is _not_ wrong, so we decide to keep it. But we thank you for pointing it out!

> "extract_answer_T3": "A_v^t", 
> "score_T3": 0    # here, wrong score: 1 -> 0

This is intentional and _not_ wrong either. The GT and extract answer produce the same math symbol. Please check 3.3 of the [paper](https://arxiv.org/pdf/2406.18521).

I'm closing the issue since both cases do not constitute incorrect grading, though we admit that the ICL for Q1 in descriptive questions makes grading more lenient for unanswerable cases by considering implicit expression of Not Applicable as correct. We'll fix it for our next version :)
