### ISSUE TITLE
Asking aboutthe whole process you use to get arxiv data

### ISSUE THREAD

**Issue by Lululzz7** [princeton-nlp/CharXiv#7]
Thank you for your wonderful and outstanding work! Could you please tell me in a little bit more detail about the whole process you use to get arxiv data? For example, including the name of the specific tool used and some other columns of information? This is very important to me! Thanks again for your great work!

**Comment by zwcolin** [comment]
We use the [bulk download option](https://info.arxiv.org/help/bulk_data_s3.html) from AWS S3 to get all arXiv papers (i.e., source files). I don't remember the details but because they are hosted via AWS S3, and you can just directly use AWS tools to download them. These source files are in the requester pays buckets so we paid a few hundred dollars when downloading all the files (we actually downloaded files from the entire arXiv to our server, and it could be cheaper if you only want to download files from a specific time frame).

If you need tool support for converting vector-based figure source files e.g., pdf eps, we have our own code to do that from arXiv source files. Please send me an email if you need it.
